import Head from "next/head";
import Link from "next/link";

const Layout = ({ children, title = "Crypo Price Tracker" }) => {
  return (
    <div className="layout">
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* <p id="head1" class="header">
        Updated Crypto prices
      </p>
      <p id="head2" class="header">
        Just
      </p>
      <p id="head3" class="header">
        For you
      </p>
      <p id="head4" class="header">
        efficient and awesome all the time
      </p>
      <p id="head5" class="header">
        Welcome to the crypto currency app
      </p>
      <div class="light x1"></div>
      <div class="light x2"></div>
      <div class="light x3"></div>
      <div class="light x4"></div>
      <div class="light x5"></div>
      <div class="light x6"></div>
      <div class="light x7"></div>
      <div class="light x8"></div>
      <div class="light x9"></div>
      <header className="header"> */}
      <header className="header">
        <Link href="/" passHref>
          <a>
           {/* adding svg */}
           LOGO to go BACK
          </a>
        </Link>
      </header>
      <main>{children}</main>
    </div>
  );
};

export default Layout;
